name: TRLC Extension Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: "Install dependencies"
        run: |
          python3 -m pip install --upgrade pip
          make install-python-deps
          npm install
      - name: "Build package"
        run: |
          npx vsce package
      - name: "Archive package"
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: "*.vsix"
