name: TRLC Extension Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:

  package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          npm install -g @vscode/vsce
      - name: Fetch CVC5 (OSX)
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "cvc5/cvc5"
          tag: "cvc5-1.0.8"
          fileName: "cvc5-macOS"
          out-file-path: "bin"
      - name: Fetch CVC5 (Windows)
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "cvc5/cvc5"
          tag: "cvc5-1.0.8"
          fileName: "cvc5-Win64.exe"
          out-file-path: "bin"
      - name: Fetch CVC5 (Windows)
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "cvc5/cvc5"
          tag: "cvc5-1.0.8"
          fileName: "cvc5-Linux"
          out-file-path: "bin"
      - name: "Build package"
        run: |
          python -m pip install --target python-deps --isolated -I --platform any --only-binary :all: -r requirements.txt
          npm install @vscode/vsce
          vsce package
      - name: "Archive package"
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: "*.vsix"
