name: TRLC Extension CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:

  lint:
    name: PyLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip --break-system-packages
          python3 -m pip install -r requirements_dev.txt --break-system-packages
      - name: Executing linter
        run: |
          make lint
