# *******************************************************************************
# TRLC VSCode Extension
# Copyright (C) 2026 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#
# This file is part of the TRLC VSCode Extension.
#
# The TRLC VSCode Extension is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# The TRLC VSCode Extension is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with TRLC. If not, see <https://www.gnu.org/licenses/>.
# *******************************************************************************
name: Reusable - Package Build

on:
  workflow_call:

jobs:
  package:
    name: Build Package
    runs-on: ubuntu-latest
    env:
      ASPECT_DISABLE_TELEMETRY: 1
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # 0.19.0
        with:
          disk-cache: true
          repository-cache: true
      - name: "Build vsix and wheel"
        run: |
          bazel build //:vsix //:wheel
          cp bazel-bin/trlc-vscode-extension.vsix .
          cp bazel-bin/src/server/trlc_lsp-*.whl .
      - name: "Package lsp4ij-template"
        run: |
          zip -r lsp4ij-template.zip lsp4ij-template/
      - name: "Archive vsix"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: package
          path: "*.vsix"
      - name: "Archive wheel"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: lsp-wheel
          path: "trlc_lsp*.whl"
      - name: "Archive lsp4ij-template"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: lsp4ij-template
          path: "lsp4ij-template.zip"
